Repository umccr/infrastructure, pull requests merged in 2022-08, with the labels that each got.

#243 Update WTS workflow inputs (dev and prod)
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request

#246 Portal TF: Disabled LINX plotting Lambda
  terraform/stacks/umccr_data_portal/cicd.tf
Labels: change request

#247 Updated production workflow of tso_ctdna
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature

#248 Update production workflow version of wts
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature

#249 Update RNAsum workflow versions
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: fix, change request
