Repository umccr/infrastructure, pull requests merged in 2022-06, with the labels that each got.

#233 WTS workflow updates
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: fix, pending apply prod

#234 Networking TF: Added ECR, ECS, Log VPC Interface Endpoints for Amazon Genomics CLI
  terraform/stacks/networking/main.tf
Labels: change request

#235 Bastion TF: Fixed properly remove packer user
  terraform/stacks/bastion/README.md
  terraform/stacks/bastion/main.tf
  terraform/stacks/bastion/outputs.tf
Labels: fix

#236 Bastion ECR TF: Created centralised Bastion ECR registry for herding container images
  terraform/stacks/bastion_ecr/.terraform.lock.hcl
  terraform/stacks/bastion_ecr/README.md
  terraform/stacks/bastion_ecr/main.tf
  terraform/stacks/bastion_ecr/policies/cross_accounts_policy_illumina.json
  terraform/stacks/bastion_ecr/policies/cross_accounts_policy_umccr.json
  terraform/stacks/bastion_ecr/policies/untagged_image_policy.json
Labels: feature
