Repository umccr/infrastructure, pull requests merged in 2022-11, with the labels that each got.

#255 Portal TF: Deprecate Portal Report processing
  terraform/stacks/umccr_data_portal/app/report.tf
Labels: change request, pending apply prod, refactor

#262 Bastion ECR TF: Bumped terraform 1.3.3 and aws provider 4.37.0
  terraform/stacks/bastion_ecr/.terraform.lock.hcl
  terraform/stacks/bastion_ecr/main.tf
Labels: dependencies

#263 Cognito AAI TF: Added Cognito AAI to Staging account
  terraform/stacks/cognito_aai/.terraform.lock.hcl
  terraform/stacks/cognito_aai/README.md
  terraform/stacks/cognito_aai/app_data_portal.tf
  terraform/stacks/cognito_aai/app_sscheck.tf
  terraform/stacks/cognito_aai/app_status_page.tf
  terraform/stacks/cognito_aai/main.tf
  terraform/stacks/cognito_aai/variables.tf
Labels: feature, dependencies

#264 Networking TF: Added Main VPC to Staging account
  terraform/stacks/networking/.terraform.lock.hcl
  terraform/stacks/networking/README.md
  terraform/stacks/networking/debug.py
  terraform/stacks/networking/main.tf
Labels: dependencies

#257 umccrise-with-germline-pipeline updates
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature, change request, pending apply prod, e2e testing required

#260 Update dev workflow with boolean requirements for dev workflows
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature, change request

#265 Portal TF: Reverted CodeBuild image to Standard 5.0
  terraform/stacks/umccr_data_portal/cicd.tf
Labels: dependencies

#261 update prod workflow input templates with required booleans and workflow versions
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature, change request, pending apply prod, e2e testing required

#266 ICA Cred CDK: Added ICA Service Token Cred for Staging
  cdk/apps/ica_credentials/app.py
  cdk/apps/ica_credentials/secrets/runtime/notify_slack/notify_slack.py
Labels: feature, change request

#267 Portal TF: Added baseline Portal infrastructure for Staging
  terraform/stacks/cognito_aai/README.md
  terraform/stacks/umccr_data_portal/README.md
  terraform/stacks/umccr_data_portal/app/s3.tf
  terraform/stacks/umccr_data_portal/athena.tf
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/main.tf
  terraform/stacks/umccr_data_portal/variables.tf
Labels: feature

#268 Portal TF: Added Staging support for ICA automated pipeline
  terraform/stacks/umccr_data_portal/workflow/README.md
  terraform/stacks/umccr_data_portal/workflow/bcl_convert.tf
  terraform/stacks/umccr_data_portal/workflow/main.tf
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
  terraform/stacks/umccr_data_portal/workflow/template/bcl_convert_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/bcl_convert_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/bcl_convert_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_stg.json
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_stg.json
  terraform/stacks/umccr_data_portal/workflow/tso_ctdna_tumor_only.tf
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
  terraform/stacks/umccr_data_portal/workflow/wgs_alignment_qc.tf
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: feature, pending apply prod, refactor, e2e testing required

#269 Portal TF: Refactored Portal baseline resources
  terraform/stacks/umccr_data_portal/backend.tf
  terraform/stacks/umccr_data_portal/backup.tf
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/frontend.tf
  terraform/stacks/umccr_data_portal/main.tf
  terraform/stacks/umccr_data_portal/monitoring.tf
  terraform/stacks/umccr_data_portal/rds.tf
  terraform/stacks/umccr_data_portal/waf.tf
Labels: refactor

#270 Portal TF: Bumped terraform 1.3.3 and aws provider 4.38.0
  terraform/stacks/umccr_data_portal/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/main.tf
  terraform/stacks/umccr_data_portal/pipeline/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/workflow/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: dependencies
