Repository umccr/infrastructure, pull requests merged in 2022-05, with the labels that each got.

#206 Added ability to build a v2 token.
  cdk/apps/ica_credentials/app.py
  cdk/apps/ica_credentials/deployment.py
  cdk/apps/ica_credentials/secrets/infrastructure.py
  cdk/apps/ica_credentials/secrets/runtime/jwt_producer/ica_common.py
  cdk/apps/ica_credentials/secrets/runtime/jwt_producer/lambda_entrypoint.py
Labels: feature, change request, pending apply prod

#225 Update Umccrise ICA CWL workflow to 2.0.2--3.9.3
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request, pending apply prod

#226 Portal TF: Added Portal UI CodeBuild env vars for GPL links
  terraform/stacks/umccr_data_portal/cicd.tf
Labels: feature, pending apply prod

#227 Cognito AAI TF: Allow Lambda Function URL invocation
  terraform/stacks/cognito_aai/policies/iam_role_authenticated_policy.json
Labels: change request, pending apply prod

#228 Initialised sqs queue for somalier extraction steps
  terraform/stacks/umccr_data_portal/pipeline/main.tf
Labels: feature, epic, pending apply prod

#230 Portal TF: Allow Portal Lambda API role and CodeBuild for ServiceDiscovery and StepFunction
  terraform/stacks/umccr_data_portal/policies/codebuild_apis_policy.json
  terraform/stacks/umccr_data_portal/policies/lambda_apis_policy.json
Labels: change request
