Repository umccr/infrastructure, pull requests merged in 2022-03, with the labels that each got.

#197 Added RNAsum-ICA to terraform
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: epic

#198 Updated bclconvert workflow
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: feature, change request

#207 Updated WTS workflow inputs
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request

#205 Updated prod versions of workflows
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: epic, change request, pending tfapply prod

#208 Portal TF: Bumped terraform 1.1.7 & aws provider 4.4.0
  terraform/stacks/umccr_data_portal/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/main.tf
  terraform/stacks/umccr_data_portal/pipeline/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/workflow/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: dependencies

#209 Updated somalier and reference file
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request, pending tfapply prod

#210 Reference data directory should be class Directory not File
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: bug, fix, pending tfapply prod

#211 Networking TF: Bumped Terraform v1.1.7
  terraform/stacks/networking/.terraform.lock.hcl
  terraform/stacks/networking/main.tf
Labels: dependencies

#212 Added blank arriba directory to dev input
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request, pending tfapply prod

#213 Added prod workflow version for rnasum
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request, pending tfapply prod

#215 Hardcode dataset for RNASum
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request

#216 Hardcode dataset for RNASum
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: change request, pending tfapply prod
