Repository umccr/infrastructure, pull requests merged in 2023-09, with the labels that each got.

#358 Portal TF: Migrating Portal DEV and STG domain name
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/frontend.tf
  terraform/stacks/umccr_data_portal/main.tf
Labels: change request

#359 Portal TF: Allowed EventBridge to send message to Portal SQS Batch queue
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/pipeline/policies/sqs_eventbridge_policy.json
Labels: fix

#349 Feature/cdk bootstrap via terraform
  terraform/stacks/cdk_bootstrap/.terraform.lock.hcl
  terraform/stacks/cdk_bootstrap/README.md
  terraform/stacks/cdk_bootstrap/bootstrap-template.yaml
  terraform/stacks/cdk_bootstrap/main.tf
Labels: feature

#334 Updated wgs alignment qc to use version 4.2.4 (dev)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_dev.json
  terraform/stacks/umccr_data_portal/workflow/wgs_alignment_qc.tf
Labels: epic

#335 Updated templates for tn to use 4.2.4 with updated reference (dev)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_dev.json
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: epic

#336 Upgraded tso ctdna workflow run template to version 1.2 (dev)
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_dev.json
  terraform/stacks/umccr_data_portal/workflow/tso_ctdna_tumor_only.tf
Labels: epic

#346 Upgrade dev WTS workflow to 4.2.4
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_dev.json
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: epic

#351 Upgrade dev RNAsum to 0.4.9
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: fix, change request

#362 umccrise: update dev to 2.3.1--1
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: change request

#341 Updated wgs alignment qc to use version 4.2.4 (stg)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_stg.json
  terraform/stacks/umccr_data_portal/workflow/wgs_alignment_qc.tf
Labels: epic

#339 Updated templates for tn to use 4.2.4 with updated reference (stg)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_stg.json
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: epic

#337 Updated tso ctdna workflow run template to version 1.2 (stg)
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_stg.json
  terraform/stacks/umccr_data_portal/workflow/tso_ctdna_tumor_only.tf
Labels: epic

#347 Upgrade stg WTS workflow to 4.2.4
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_stg.json
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: epic

#352 Upgrade stg RNAsum to 0.4.9
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: fix, change request

#363 umccrise: update stg to 2.3.1--1
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: change request
