Repository umccr/infrastructure, pull requests merged in 2023-11, with the labels that each got.

#338 Updated tso ctdna workflow run template to version 1.2 (prod)
  terraform/stacks/umccr_data_portal/workflow/template/tso_ctdna_tumor_only_prod.json
  terraform/stacks/umccr_data_portal/workflow/tso_ctdna_tumor_only.tf
Labels: epic, e2e testing required

#340 Updated templates for tn to use 4.2.4 with updated reference (prod)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_prod.json
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: epic, e2e testing required

#342 Updated wgs alignment qc to use version 4.2.4 (prod)
  terraform/stacks/umccr_data_portal/workflow/template/wgs_alignment_qc_prod.json
  terraform/stacks/umccr_data_portal/workflow/wgs_alignment_qc.tf
Labels: epic, e2e testing required

#348 Upgrade prod WTS workflow to 4.2.4
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_prod.json
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: epic, e2e testing required

#353 Upgrade prod RNAsum to 0.4.9
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: fix, change request, e2e testing required

#371 umccrise: update prod to 2.3.1--1
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: change request, e2e testing required

#385 Upgrade bclconvert version commit id
  terraform/stacks/umccr_data_portal/workflow/bcl_convert.tf
Labels: fix, e2e testing required

#387 Ica/add GitHub actions role
  cdk/apps/ica_credentials/app.py
  cdk/apps/ica_credentials/deployment.py
  cdk/apps/ica_credentials/secrets/infrastructure.py
Labels: feature
