Repository umccr/infrastructure, pull requests merged in 2023-07, with the labels that each got.

#329 Portal TF: Added oncoanalyser output bucket to Portal indexing
  terraform/stacks/umccr_data_portal/app/policies/sqs_s3_primary_data_event_policy.json
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: feature, pending apply prod

#330 Data TF: Harmonised BYOB data prod S3 prefix to `analysis_data/`
  terraform/stacks/data_archive/README.md
  terraform/stacks/data_archive/byob_ica_v2.tf
  terraform/stacks/data_archive/main.tf
Labels: fix

#331 Restrict Deep Archive transition
  terraform/stacks/data_archive/main.tf
  terraform/stacks/data_archive/raw_data_archive.tf
Labels: change request

#332 Need to split lifecycle rule
  terraform/stacks/data_archive/raw_data_archive.tf
Labels: fix
