Repository umccr/infrastructure, pull requests merged in 2023-03, with the labels that each got.

#283 GPL CI/CD URL Removal
  terraform/stacks/umccr_data_portal/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/data2.tf
Labels: change request, pending apply prod

#280 Update WTS multiqc config value
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_prod.json
  terraform/stacks/umccr_data_portal/workflow/template/wts_tumor_only_stg.json
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: change request, pending apply prod

#284 Update dev workflow ids for somatic and umccrise
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_dev.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: change request

#286 Update umccrise dev workflow version
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: bug

#293 Datalake TF: Upgraded Terraform 1.4.2
  terraform/stacks/umccr_datalake/.terraform.lock.hcl
  terraform/stacks/umccr_datalake/main.tf
Labels: dependencies

#287 Updated tumor normal staging input template
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_stg.json
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: change request, e2e testing required

#288 Updated umccrise template and workflow version
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_stg.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: change request, e2e testing required

#289 Update rnasum workflow version to use more appropriate resources
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: fix, e2e testing required

#290 Networking TF: Upgraded Terraform 1.4.2 and fixed subnets for VPC endpoint interface
  terraform/stacks/networking/.terraform.lock.hcl
  terraform/stacks/networking/main.tf
Labels: change request, pending apply prod

#292 Cognito AAI TF: Upgraded Terraform 1.4.2
  terraform/stacks/cognito_aai/.terraform.lock.hcl
  terraform/stacks/cognito_aai/main.tf
Labels: dependencies, pending apply prod

#294 Portal TF: Bumped RDS MySQL minor patch version 8.0.mysql_aurora.3.02.2
  terraform/stacks/umccr_data_portal/rds.tf
Labels: dependencies
