Repository umccr/infrastructure, pull requests merged in 2023-04, with the labels that each got.

#295 Update production tumor normal workflow id and version to also run germline tool
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_prod.json
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: change request, e2e testing required

#296 No longer run germline with umccrise, instead germline is run with somatic
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_prod.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: change request, e2e testing required

#297 Update RNASum workflow version to use more appropriate resources
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: fix, e2e testing required

#279 New app: Dracarys
  cdk/apps/dracarys/README.md
  cdk/apps/dracarys/app.py
  cdk/apps/dracarys/cdk.json
  cdk/apps/dracarys/dracarys/__init__.py
  cdk/apps/dracarys/dracarys/dracarys_stack.py
  cdk/apps/dracarys/lambda/Dockerfile
  cdk/apps/dracarys/lambda/lambda.py
  cdk/apps/dracarys/lambda/requirements.txt
  cdk/apps/dracarys/lambda/test/test_docker_run.sh
  cdk/apps/dracarys/lambda/test/test_queue_msg.json
  cdk/apps/dracarys/lambda/test/test_queue_msg.sh
  cdk/apps/dracarys/requirements.txt
  terraform/stacks/umccr_data_portal/pipeline/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/pipeline/main.tf
Labels: epic

#299 Update bastion ecr permissions for oncoanalyser repo
  terraform/stacks/bastion_ecr/main.tf
Labels: feature

#300 Bastion ECR TF: Added Staging for cross accounts access container images
  terraform/stacks/bastion_ecr/policies/cross_accounts_policy_umccr.json
Labels: change request

#304 Eliminate the precursor, PoC, to OrcaBus
  cdk/apps/thebus/.gitignore
  cdk/apps/thebus/Makefile
  cdk/apps/thebus/README.md
  cdk/apps/thebus/app.py
  cdk/apps/thebus/cdk.json
  cdk/apps/thebus/lambdas/functions/bcl_convert/bcl_convert.py
  cdk/apps/thebus/lambdas/functions/dragen_wgs_qc/dragen_wgs_qc.py
  cdk/apps/thebus/lambdas/functions/dragen_wgs_somatic/dragen_wgs_somatic.py
  cdk/apps/thebus/lambdas/functions/ens_event_manager/ens_event_manager.py
  cdk/apps/thebus/lambdas/functions/gds_manager/gds_manager.py
  cdk/apps/thebus/lambdas/functions/gds_manager/requirements.txt
  cdk/apps/thebus/lambdas/functions/orchestrator/orchestrator.py
  cdk/apps/thebus/lambdas/functions/orchestrator/requirements.txt
  cdk/apps/thebus/lambdas/functions/wes_launcher/wes_launcher.py
  cdk/apps/thebus/lambdas/layers/create_layer_package.sh
  cdk/apps/thebus/lambdas/layers/domain/model/data_file.py
  cdk/apps/thebus/lambdas/layers/domain/model/library.py
  cdk/apps/thebus/lambdas/layers/domain/model/sequence_run.py
  cdk/apps/thebus/lambdas/layers/domain/model/subject.py
  cdk/apps/thebus/lambdas/layers/eb_util/eb_util.py
  cdk/apps/thebus/lambdas/layers/eb_util/requirements.txt
  cdk/apps/thebus/lambdas/layers/schemas/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/requirements.txt
  cdk/apps/thebus/lambdas/layers/schemas/schema/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/sequencerunstatechange/Event.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/sequencerunstatechange/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/sequencerunstatechange/marshaller.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/weslaunchrequest/Event.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/weslaunchrequest/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/weslaunchrequest/marshaller.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrequest/Event.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrequest/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrequest/marshaller.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrunstatechange/Event.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrunstatechange/__init__.py
  cdk/apps/thebus/lambdas/layers/schemas/schema/workflowrunstatechange/marshaller.py
  cdk/apps/thebus/requirements.txt
  cdk/apps/thebus/schema/BclConvertWorkflowRequest.json
  cdk/apps/thebus/schema/DragenWgsQcWorkflowRequest.json
  cdk/apps/thebus/schema/SequenceRunStateChange.json
  cdk/apps/thebus/schema/WesLaunchRequest.json
  cdk/apps/thebus/schema/WorkflowRequest.json
  cdk/apps/thebus/schema/WorkflowRunStateChange.json
  cdk/apps/thebus/setup.py
  cdk/apps/thebus/stacks/schema_stack.py
  cdk/apps/thebus/stacks/thebus_stack.py
Labels: refactor
