Repository umccr/infrastructure, pull requests merged in 2023-08, with the labels that each got.

#333 Added 3rd party construct that does cleaning of CDK assets
  cdk/apps/cleaner/.gitignore
  cdk/apps/cleaner/README.md
  cdk/apps/cleaner/cdk.json
  cdk/apps/cleaner/cleaner.ts
  cdk/apps/cleaner/lib/cleaner-stack.ts
  cdk/apps/cleaner/package-lock.json
  cdk/apps/cleaner/package.json
  cdk/apps/cleaner/tsconfig.json
Labels: feature

#343 Networking TF: Deployed main-vpc into AGHA account
  terraform/stacks/networking/.terraform.lock.hcl
  terraform/stacks/networking/README.md
  terraform/stacks/networking/main.tf
Labels: feature, dependencies, pending apply prod

#344 Update years in tracking sheet SBJ generator script
  scripts/umccr_pipeline/UMCCR_Library_Tracking_MetaData.js
Labels: change request

#345 Update lambda_apis_policy.json
  terraform/stacks/umccr_data_portal/policies/lambda_apis_policy.json
Labels: change request, pending apply prod

#355 Portal TF: Added data pipeline plumbing from Oncoanalyser NF to Portal
  terraform/stacks/umccr_data_portal/app/README.md
  terraform/stacks/umccr_data_portal/pipeline/README.md
  terraform/stacks/umccr_data_portal/pipeline/holmes.tf
  terraform/stacks/umccr_data_portal/pipeline/ica.tf
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/pipeline/oncoanalyser.tf
Labels: feature, epic, pending apply prod, e2e testing required

#356 Add SQS queue for star alignment jobs
  terraform/stacks/umccr_data_portal/pipeline/oncoanalyser.tf
Labels: feature, epic, pending apply prod, e2e testing required

#357 Add sash ECR repo in Bastion and allow across account access
  terraform/stacks/bastion_ecr/main.tf
Labels: feature
