Repository umccr/infrastructure, pull requests merged in 2023-10, with the labels that each got.

#366 Update WTS stg workflow version
  terraform/stacks/umccr_data_portal/workflow/wts_tumor_only.tf
Labels: fix

#367 Portal TF: Switched Portal CodeBuild to ARM_CONTAINER with Python3.11 Node18
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/data2.tf
Labels: dependencies, pending apply prod

#368 Portal TF: Rollback CodeBuild to LINUX_CONTAINER x86_64 Standard image
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/data2.tf
Labels: dependencies

#372 Update bcl convert workflow version for `dev`
  terraform/stacks/umccr_data_portal/workflow/bcl_convert.tf
Labels: fix

#373 Portal TF: Added wts_alignment_qc workflow type SSM parameter
  terraform/stacks/umccr_data_portal/workflow/wgs_alignment_qc.tf
Labels: fix, pending apply prod

#377 Portal TF: Bumped terraform 1.5.7 & aws provider 5.21.0
  terraform/stacks/umccr_data_portal/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/main.tf
  terraform/stacks/umccr_data_portal/pipeline/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/pipeline/main.tf
  terraform/stacks/umccr_data_portal/workflow/.terraform.lock.hcl
  terraform/stacks/umccr_data_portal/workflow/main.tf
Labels: dependencies

#378 Cognito AAI TF: Bumped terraform 1.5.7 & aws provider 5.21.0
  terraform/stacks/cognito_aai/.terraform.lock.hcl
  terraform/stacks/cognito_aai/main.tf
Labels: dependencies

#379 Bastion ECR TF: Bumped terraform 1.5.7 & aws provider 5.21.0
  terraform/stacks/bastion_ecr/.terraform.lock.hcl
  terraform/stacks/bastion_ecr/main.tf
Labels: dependencies

#380 Networking TF: Bumped terraform 1.5.7 & aws provider 5.21.0
  terraform/stacks/networking/.terraform.lock.hcl
  terraform/stacks/networking/main.tf
Labels: dependencies, pending apply prod

#381 Portal TF: Reroute Portal DLQ alarms to proper Slack channels
  terraform/stacks/umccr_data_portal/app/gds.tf
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/app/s3.tf
  terraform/stacks/umccr_data_portal/pipeline/main.tf
Labels: change request, pending apply prod

#383 Portal TF: Updated EventBridge event pattern to only capture nextflow-stack
  terraform/stacks/umccr_data_portal/pipeline/oncoanalyser.tf
Labels: fix

#384 Upgrade bclconvert version commit id
  terraform/stacks/umccr_data_portal/workflow/bcl_convert.tf
Labels: fix, e2e testing required

#386 Slack CDK: Improved multi-accounts slacker
  cdk/apps/slack/README.md
  cdk/apps/slack/app.py
  cdk/apps/slack/lambdas/batch/notify_slack.py
  cdk/apps/slack/package-lock.json
  cdk/apps/slack/package.json
  cdk/apps/slack/requirements.txt
  cdk/apps/slack/setup.py
  cdk/apps/slack/stacks/slack_lambda.py
Labels: dependencies, fix, pending apply prod
