Repository umccr/infrastructure, pull requests merged in 2023-05, with the labels that each got.

#305 Updated staging workflow versions and template for tn and umccrise
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_stg.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: feature, fix

#306 Networking TF: Removed all Interface Endpoints from Main VPC
  terraform/stacks/networking/main.tf
Labels: fix, change request

#307 Allow cross-account-sharing for star-align-nf ECR
  terraform/stacks/bastion_ecr/main.tf
Labels: feature

#308 Updated prod workflow versions and template for tn and umccrise
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_prod.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
  terraform/stacks/umccr_data_portal/workflow/wgs_tumor_normal.tf
Labels: feature, fix

#312 Fix missing T/N workflow parameter
  terraform/stacks/umccr_data_portal/workflow/template/wgs_tumor_normal_prod.json
Labels: fix

#309 Update umccrise dev version to 2.3.0
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_dev.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: feature, fix, e2e testing required

#314 HOTFIX: TF data archive - Update oncoanalyser bucket lifecycle
  terraform/stacks/data_archive/oncoanalyser.tf
Labels: fix

#315 Update Batch Slack notifier queue selection
  cdk/apps/slack/stacks/slack_lambda.py
Labels: feature, change request, pending apply prod

#316 Update rnasum dev verison to 0.4.7
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: bug, fix

#310 Update umccrise for 2.3.0 for staging env
  terraform/stacks/umccr_data_portal/workflow/template/umccrise_stg.json
  terraform/stacks/umccr_data_portal/workflow/umccrise.tf
Labels: feature, fix, e2e testing required

#318 Update rnasum stg verison to 0.4.7
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: bug, fix, e2e testing required
