Repository umccr/infrastructure, pull requests merged in 2024-05, with the labels that each got.

#419 Update RNAsum dev to 0.6.5
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_dev.json
Labels: change request

#423 Update RNAsum stg to 0.6.5
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_stg.json
Labels: change request, e2e testing required

#421 Portal TF: Bumped Aurora MySQL Engine minor version as recommended
  terraform/stacks/umccr_data_portal/rds.tf
Labels: change request, pending apply prod

#420 TF data-portal: increase RDS max capacity to 32 for prod
  terraform/stacks/umccr_data_portal/variables.tf
Labels: change request

#416 Portal TF: Deprecated data domain and related SSL SSM parameters
  terraform/stacks/umccr_data_portal/backend.tf
Labels: change request, pending apply prod

#415 Cognito AAI TF: Enabled new feature `prevent_user_existence_errors` check
  terraform/stacks/cognito_aai/app_data_portal_data2.tf
Labels: feature, pending apply prod

#422 TF data archive: update bucket name to match convention
  terraform/stacks/data_archive/byob_ica_v2.tf
  terraform/stacks/data_archive/fastq_archive.tf
  terraform/stacks/data_archive/raw_data_archive.tf
Labels: change request

#425 Update Input Keys
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_dev.json
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_stg.json
Labels: feature, e2e testing required

#431 Update RNAsum stg workflow version
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: feature
