Repository umccr/infrastructure, pull requests merged in 2024-09, with the labels that each got.

#472 add orcaui dev page config
  terraform/stacks/cognito_aai/app_orcaui.tf
Labels: feature, change request

#475 Feat: Update ICA BYOB cors config
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature

#477 data_archive TF: Added setup requirement about icav2 storageConfiguration API access
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: documentation

#478 Networking TF: Reverted back public IP for prod only
  terraform/stacks/networking/main.tf
Labels: change request
