Repository umccr/infrastructure, pull requests merged in 2024-11, with the labels that each got.

#493 Add object tagging permissions to ICA IAM user
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: fix

#494 Update ica cross account role - add DeleteObject
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: fix

#497 Chore: Cognito App Client Cleanup
  terraform/stacks/cognito_aai/README.md
  terraform/stacks/cognito_aai/app_status_page.tf
Labels: pending apply prod, refactor

#498 Feat(data-portal): Update IAM Role
  terraform/stacks/umccr_data_portal/backend.tf
Labels: feature, pending apply prod

#503 Disable assigning public ip by default in main-vpc
  terraform/stacks/networking/main.tf
Labels: change request, pending apply prod

#505 ICA ENS TF: Decommissioned ica_ens stack
  terraform/stacks/ica_ens/README.md
  terraform/stacks/ica_ens/main.tf
Labels: change request

#508 feat(tf-unimelb): grant data mover role permissions
  terraform/stacks/unimelb/data_archive/analysis_archive.tf
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
Labels: feature
