Repository umccr/infrastructure, pull requests merged in 2024-12, with the labels that each got.

#509 Portal TF: Tuned aurora with reader endpoint
  terraform/stacks/umccr_data_portal/rds.tf
  terraform/stacks/umccr_data_portal/variables.tf
Labels: change request

#510 Portal TF: Route alerts to newer ops channels for notification harmonisation
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/app/s3.tf
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/monitoring.tf
  terraform/stacks/umccr_data_portal/pipeline/main.tf
Labels: change request

#507 Update dev bucket policy for Access Point support
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature

#514 Add read only blanket access statement to bucket policy of analysis …
  terraform/stacks/unimelb/data_archive/analysis_archive.tf
Labels: change request

#511 Slack CDK: Route alerts to newer ops channels for notification harmonisation
  cdk/apps/slack/app.py
Labels: change request

#516 Portal TF: Scaling back down aurora
  terraform/stacks/umccr_data_portal/rds.tf
  terraform/stacks/umccr_data_portal/variables.tf
Labels: change request

#517 Portal TF: Route archive buckets notification to Portal SQS
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: change request

#518 Portal TF: Switched Portal CodeBuild to ARM_CONTAINER aarch64
  terraform/stacks/umccr_data_portal/cicd.tf
  terraform/stacks/umccr_data_portal/data2.tf
Labels: change request

#519 Update UMCCR_Library_Tracking_MetaData.js
  scripts/umccr_pipeline/UMCCR_Library_Tracking_MetaData.js
Labels: change request

#520 agha-infra: Deep Archive S3 for MM data
  terraform/stacks/agha_infra/.terraform.lock.hcl
  terraform/stacks/agha_infra/main.tf
Labels: infrastructure

#521 data_archive TF: Enabled fastq archive lifecycle rule
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
Labels: change request

#523 Portal TF: Forward archive buckets S3 event to Portal ingestion
  terraform/stacks/umccr_data_portal/app/policies/sqs_s3_primary_data_event_policy.json
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: change request
