Repository umccr/infrastructure, pull requests merged in 2024-07, with the labels that each got.

#452 Data Archive TF: Updated BYOB bucket events forward to Staging
  terraform/stacks/unimelb/data_archive/.terraform.lock.hcl
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature

#453 Networking TF: Disabled assigning public IP by default in main-vpc
  terraform/stacks/networking/main.tf
Labels: change request

#454 Update RNAsum dev version
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: feature

#455 Update RNAsum stg version
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
Labels: feature

#429 Update RNAsum prod to 1.1.0
  terraform/stacks/umccr_data_portal/workflow/rnasum.tf
  terraform/stacks/umccr_data_portal/workflow/template/rnasum_prod.json
Labels: feature, pending apply prod

#456 Data Archive TF: Updated BYOB bucket events forward to Production
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature, pending apply prod

#457 Data Archive TF: Updated BYOB bucket to allow HeadObject
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: change request

#458 Portal TF: Added SecurityHeadersPolicy to cloudfront cache behaviour
  terraform/stacks/umccr_data_portal/frontend.tf
  terraform/stacks/umccr_data_portal/variables.tf
Labels: fix, change request

#459 ICA ENS TF: Added ICA ENS subscription SQS queue
  terraform/stacks/ica_ens/.terraform.lock.hcl
  terraform/stacks/ica_ens/README.md
  terraform/stacks/ica_ens/main.tf
  terraform/stacks/ica_ens/outputs.tf
  terraform/stacks/ica_ens/policies/sqs_ica_ens_policy.json
Labels: feature

#461 Portal TF: Added SecurityHeadersPolicy-With-CSP to cloudfront cache behaviour
  terraform/stacks/umccr_data_portal/frontend.tf
Labels: fix, change request

#462 Portal TF: Minor tuning SecurityHeadersPolicy-With-CSP policy for prod
  terraform/stacks/umccr_data_portal/data2.tf
  terraform/stacks/umccr_data_portal/frontend.tf
Labels: fix
