Repository umccr/infrastructure, pull requests merged in 2024-06, with the labels that each got.

#433 modify status page callback and redirect url in dev env
  terraform/stacks/cognito_aai/app_status_page.tf
Labels: change request, pending apply prod

#436 Feature/data s3 event forward
  terraform/stacks/data_archive/byob_ica_v2.tf
Labels: feature

#438 Portal TF: Added Portal S3 indexer to ICAv2 pipeline cache bucket for ctTSOv2 result
  terraform/stacks/umccr_data_portal/app/main.tf
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: feature, pending apply prod

#439 Portal TF: Updated Portal S3 ingestion SQS policy
  terraform/stacks/umccr_data_portal/app/policies/sqs_s3_primary_data_event_policy.json
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: fix, pending apply prod

#440 feat(orcabus): add permissions for the filemanager ingest role to access pipeline buckets.
  terraform/stacks/data_archive/byob_ica_v2.tf
Labels: feature, infrastructure

#442 Resolve Invalid Principal error by commenting out offending config
  terraform/stacks/data_archive/byob_ica_v2.tf
Labels: fix

#443 Update data cache buckets policies to grant data portal access
  terraform/stacks/data_archive/byob_ica_v2.tf
Labels: feature

#445 Move data archive stack under unimelb
  terraform/stacks/unimelb/data_archive/.terraform.lock.hcl
  terraform/stacks/unimelb/data_archive/README.md
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
  terraform/stacks/unimelb/data_archive/main.tf
  terraform/stacks/unimelb/data_archive/oncoanalyser.tf
  terraform/stacks/unimelb/data_archive/raw_data_archive.tf
  terraform/stacks/unimelb/data_archive/variables.tf
Labels: refactor
