Repository umccr/infrastructure, pull requests merged in 2024-10, with the labels that each got.

#479 feat: add object tagging permissions for orcabus file manager
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature, change request

#480 add portal url in allowed_origins
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: feature

#482 Add ICAv2 BYOB for longread account
  terraform/stacks/unimelb/longread/byob_ica_v2.tf
  terraform/stacks/unimelb/longread/main.tf
Labels: feature, infrastructure

#484 Updated README
  README.md
Labels: fix

#483 Portal TF: Added Batch EventBridge rule to exclude oncoanalyser events from orcabus
  terraform/stacks/umccr_data_portal/pipeline/oncoanalyser.tf
Labels: change request, pending apply prod

#487 Feat: Add New Admin Cognito User Group
  terraform/stacks/cognito_aai/app_orcaui.tf
  terraform/stacks/cognito_aai/main.tf
Labels: feature, pending apply prod

#489 Portal TF: Added event rule filter on BYOB cache prefix
  terraform/stacks/umccr_data_portal/app/s3.tf
Labels: change request, pending apply prod
