Repository umccr/infrastructure, pull requests merged in 2024-04, with the labels that each got.

#412 Cognito AAI TF: Implemented a way to create Service User with Cognito
  terraform/stacks/cognito_aai/app_data_portal_data2.tf
  terraform/stacks/cognito_aai/main.tf
  terraform/stacks/cognito_aai/outputs.tf
  terraform/stacks/cognito_aai/users.tf
Labels: feature, change request

#413 Updates to data archive TF stack
  terraform/stacks/data_archive/byob_ica_v2.tf
  terraform/stacks/data_archive/fastq_archive.tf
Labels: uom migration

#417 Fix Oncoanalyser bucket policy
  terraform/stacks/data_archive/oncoanalyser.tf
Labels: fix
