Repository umccr/infrastructure, pull requests merged in 2024-08, with the labels that each got.

#375 Created three stacks for development for testing the icav2 credentials
  cdk/apps/icav2_credentials/.gitignore
  cdk/apps/icav2_credentials/.npmignore
  cdk/apps/icav2_credentials/README.md
  cdk/apps/icav2_credentials/bin/icav2_credentials.ts
  cdk/apps/icav2_credentials/cdk.json
  cdk/apps/icav2_credentials/jest.config.js
  cdk/apps/icav2_credentials/lambdas/icav2_jwt_producer/__init__.py
  cdk/apps/icav2_credentials/lambdas/icav2_jwt_producer/ica_common.py
  cdk/apps/icav2_credentials/lambdas/icav2_jwt_producer/lambda_entrypoint.py
  cdk/apps/icav2_credentials/lambdas/icav2_jwt_producer/secret_manager_common.py
  cdk/apps/icav2_credentials/lambdas/slack_notifier/lambda_entrypoint.py
  cdk/apps/icav2_credentials/lambdas/slack_notifier/notify_slack.py
  cdk/apps/icav2_credentials/lib/icav2_credentials-stack.ts
  cdk/apps/icav2_credentials/package-lock.json
  cdk/apps/icav2_credentials/package.json
  cdk/apps/icav2_credentials/scripts/update_api_key.sh
  cdk/apps/icav2_credentials/test/icav2_credentials.test.ts
  cdk/apps/icav2_credentials/tsconfig.json
Labels: feature

#470 ICAv2 Cred CDK: Fixed script API key name for DEV
  cdk/apps/icav2_credentials/scripts/update_api_key.sh
Labels: fix

#469 ICA ENS TF: Configured ICA ENS subscribed `bssh.runs` event SQS to delayed queue
  terraform/stacks/ica_ens/main.tf
Labels: change request

#471 Remove legacy pipeline cache
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
Labels: change request
