Repository umccr/infrastructure, pull requests merged in 2025-02, with the labels that each got.

#533 Feat(cognito_aai): Add curator Cognito User Pool Group
  terraform/stacks/cognito_aai/main.tf
Labels: feature, pending apply prod

#537 Update the lifecycle configuration of the prod BYOB bucket
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: change request

#538 feat(tf-unimelb): add filemanager presign user permissions
  terraform/stacks/unimelb/data_archive/analysis_archive.tf
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: change request

#540 Bastion ECR: Added `orcavault-dbt` container image repo
  terraform/stacks/bastion_ecr/main.tf
Labels: feature
