Repository umccr/infrastructure, pull requests merged in 2025-01, with the labels that each got.

#522 data_archive TF: Fixed lifecycle policy reflow ordering issue
  terraform/stacks/unimelb/data_archive/analysis_archive.tf
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
  terraform/stacks/unimelb/data_archive/oncoanalyser.tf
Labels: fix

#524 data_archive TF: Added steps-s3-copy role for restore and share access from archive buckets
  terraform/stacks/unimelb/data_archive/analysis_archive.tf
  terraform/stacks/unimelb/data_archive/fastq_archive.tf
Labels: change request

#529 Allow retrieval of object tags for default cross account access
  terraform/stacks/unimelb/data_archive/byob_ica_v2.tf
Labels: fix

#526 Networking TF: Added EC2 Instance Connect Endpoint (EICE)
  terraform/stacks/networking/main.tf
Labels: feature

#527 Networking TF: Fixed VPC Gateway S3 and DynamoDB endpoints to db route table ids
  terraform/stacks/networking/main.tf
Labels: fix
